# See https://docs.redoc.ly/cli/configuration/ for more information.
organization: schoolbox
extends:
  - recommended
apis:
  main:
    root: openapi/openapi.yaml
    output: ./docs/
rules:
  no-empty-servers: off
  info-license: off
  operation-4xx-response: off
  no-invalid-media-type-examples: off
theme:
  openapi:
    htmlTemplate: ./docs/template.html
    theme:
      colors:
        primary:
          main: "#32329f"
