# See https://docs.redoc.ly/cli/configuration/ for more information.
apis:
  main:
    root: openapi/openapi.yaml
rules:
  no-empty-servers: off
  info-license: off
  operation-4xx-response: off
features.openapi:
  htmlTemplate: ./docs/template.html
  theme:
    colors:
      primary:
        main: "#32329f"
