type: object
required:
  - value
properties:
  value:
    oneOf:
      - type: string
      - type: number
      - type: boolean
      - type: object
        additionalProperties: true
      - type: array
        items: {}
    description: The new configuration value. Can be any valid JSON type depending on the config setting.
    example:
      string_value: "Updated School Name"
      number_value: 52428800
      boolean_value: false
      object_value:
        primaryColor: "#2563eb"
        secondaryColor: "#64748b"
        darkMode: true
      array_value: ["pdf", "doc", "docx", "jpg", "png"]