name: publish-spec-master

# Publish of production specs happens on release.
on:
  release:
    types:
      - released
jobs:
  build:
    if: github.repository == 'alaress/schoolbox-api-docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.0
      - name: Push to gh-pages branch
        id: publish-spec-master
        run: |
          # Commit on behalf of the github-actions bot
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Copy docs into gh-pages repo
          # Also copy openapi/ and .redocly.yaml (for building docs)
          mkdir .staging/
          cp -r docs/ openapi/ .redocly.yaml .staging
          git checkout -- .
          git checkout gh-pages
          cp -r .staging/* .
          rm -rf .staging/

          # Build the docs
          npm ci
          npm run rebuild-builds-list
          npm run build --build-version=${{ github.ref_name }} --selected

          # Commit and push
          git add -f docs/builds docs/builds.json
          git commit --allow-empty -m "Publish spec for beta release ${{ github.ref_name }}" .
          git push
